server:
  port: 8383


spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/user?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&autoReconnect=true
    username: admin
    password: admin
    driverClassName: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource


  freemarker:
    cache: false
    templateEncoding: UTF-8
    templateLoaderPath: classpath:/templates/  #表示所有的模板文件都在该目录下,也即是前端文件在该目录下
    suffix: .html
    settings:
      locale: zh_CN
      date_format: yyyy-MM-dd
      time_format: HH:mm:ss
      datetime_format: yyyy-MM-dd HH:mm:ss



logging:
  level.com.test.data: debug